[package]
name = "zellij-worktree"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
zellij-tile = "0.45.1"
yansi = "1.0"
sha2 = "0.10"
shellexpand = { version = "3.1", default-features = false, features = ["base-0"] }

[profile.release]
lto = true
opt-level = "z"
strip = true
codegen-units = 1
